### ISSUE TITLE
Would you like to add size-limit ?)

### ISSUE THREAD

**Issue by irustm** [DenysVuika/preact-translate#1]
https://github.com/ai/size-limit ?
Size Limit will prevent mistakes: is somebody will send PR, Size Limit will check it on CI.

cc @ai

**Comment by ai** [comment]
In your case, you need to set `webpack: false` in Size Limit config and run Size Limit after Rollup with build file in `path`

**Comment by DenysVuika** [comment]
Good point, thanks. I will try to integrate it. Right now the umd version is ±1kb gzipped and I will try to keep the library as small as possible.
