### ISSUE TITLE
TranslateProvider trying to fetch assets/en.json even if translations key is passed

### ISSUE THREAD

**Issue by toniopelo** [DenysVuika/preact-translate#195]
The following code:
```
<TranslateProvider translations={{ fr: phrases, en: {} }} lang="fr">
  ...
</TranslationProvider>
```

Is still producing a xhr call to fetch `assets/en.json`, see this console output:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9287511/83780520-8dede880-a68d-11ea-8fe3-9cb1474bec1b.png">

**Comment by toniopelo** [comment]
Ok, finally found out that the problem is on that we fetch translations if their land object is empty (even though the key exists).
In my case I don't want to support English now but I'm not able to change the `fallbackLang`. So I need to have an `en` key on the translation object.

I submitted two PRs:
#197 Which allow to update the `fallbackLang` (This is preferred way IMO)
#196 Optionally we could also avoid fetching translations if the key exists (whether or not they contain an empty object)

**Comment by DenysVuika** [comment]
Thanks for the contribution!
